#!/bin/bash
#'V3.5'#
####################################<
### "BY ACKHTTP SERVER MANAGER >> @GODYSKYUP <<" ###
####################################<
user=$(whoami)
if [ "$user" != "root" ]; then
echo "DEVE SER EXECUTADO COMO ROOT! >> SUDO -I <<"
fi
#"0"
#### "VM" ###
echo 33554432 > /proc/sys/vm/overcommit_ratio
echo 1048576 > /proc/sys/fs/nr_open
echo 1048576 > /proc/sys/fs/file-max
echo 1048567 > /proc/sys/vm/max_map_count
echo 1000 > /proc/sys/vm/watermark_scale_factor
echo 1000 > /proc/sys/vm/dirty_expire_centisecs
echo 100 > /proc/sys/vm/dirty_writeback_centisecs
echo 200 > /proc/sys/vm/vfs_cache_pressure
echo 100 > /proc/sys/vm/swappiness
echo 30 > /proc/sys/vm/dirty_ratio
echo 16 > /proc/sys/vm/page-cluster
echo 5 > /proc/sys/vm/dirty_background_ratio
echo 1 > /proc/sys/vm/legacy_va_layout
echo 1 > /proc/sys/vm/overcommit_memory
echo 1 > /proc/sys/vm/memory_failure_early_kill
#"1"
#### "KERNEL" ###
echo 800000000 > /proc/sys/kernel/sched_migration_cost_ns
echo 33554432 > /proc/sys/kernel/pty/max
echo 33554432 > /proc/sys/kernel/threads-max
echo 1000000 > /proc/sys/kernel/sched_latency_ns
echo 4194303 > /proc/sys/kernel/pid_max
echo 65535 > /proc/sys/kernel/msgmnb
echo 65535 > /proc/sys/kernel/msgmax
echo 32768 > /proc/sys/kernel/sched_nr_migrate
echo 10000 > /proc/sys/kernel/sched_wakeup_granularity_ns
echo 1 > /proc/sys/kernel/sched_tunable_scaling
echo 01 > /proc/sys/kernel/sched_cfs_bandwidth_slice_us
echo -1 > /proc/sys/kernel/sched_rt_runtime_us
echo -1 > /proc/sys/kernel/sched_rt_period_us
echo -1 >/proc/sys/kernel/sched_rr_timeslice_ms
echo 0 > /proc/sys/kernel/sched_autogroup_enabled
#"2"
### "NET.CORE EM GERAL" ###
echo 200000000 > /proc/sys/net/core/optmem_max
echo 33554432 > /proc/sys/net/core/somaxconn
echo 33554432 > /proc/sys/net/core/netdev_max_backlog
echo 33554432 > /proc/sys/net/core/flow_limit_table_len
echo 33554432 > /proc/sys/net/unix/max_dgram_qlen
echo 33554432 > /proc/sys/net/core/dev_weight
echo 50000 > /proc/sys/net/core/netdev_budget
echo 8000 > /proc/sys/net/core/netdev_budget_usecs
echo 50 > /proc/sys/net/core/busy_read
echo 50 > /proc/sys/net/core/busy_poll
echo illinois > /proc/sys/net/ipv4/tcp_congestion_control
echo illinois > /proc/sys/net/ipv4/tcp_allowed_congestion_control
echo fq > /proc/sys/net/core/default_qdisc
#"3"
### "TEMPO DE CONEXAO TCP" ###
echo 7200 > /proc/sys/net/ipv4/tcp_keepalive_time
echo 3000 > /proc/sys/net/ipv4/tcp_thin_linear_timeouts
echo 60 > /proc/sys/net/ipv4/tcp_keepalive_intvl
echo 15 > /proc/sys/net/ipv4/tcp_keepalive_probes
echo 10 > /proc/sys/net/ipv4/tcp_synack_retries
echo 7 > /proc/sys/net/ipv4/tcp_syn_retries
echo 5 > /proc/sys/net/ipv4/tcp_fin_timeout
#"4"
### "TCP" ###
echo 60000 65535 > /proc/sys/net/ipv4/ip_local_port_range
echo 33554432 > /proc/sys/net/ipv4/tcp_max_syn_backlog
echo 33554432 > /proc/sys/net/ipv4/tcp_max_tw_buckets
echo 33554432 > /proc/sys/net/ipv4/tcp_max_reordering
echo 33554432 > /proc/sys/net/ipv4/neigh/default/unres_qlen_bytes
echo 33554432 > /proc/sys/net/ipv4/tcp_fastopen
echo 3276800 > /proc/sys/net/ipv4/tcp_limit_output_bytes
echo 2500000 > /proc/sys/net/ipv4/tcp_comp_sack_delay_ns
echo 983040 > /proc/sys/net/ipv4/tcp_notsent_lowat
echo 262144 > /proc/sys/net/ipv4/tcp_max_orphans
echo 1800 > /proc/sys/net/ipv4/route/mtu_expires
echo 1460 > /proc/sys/net/ipv4/tcp_base_mss
echo 1024 > /proc/sys/net/ipv4/tcp_min_rtt_wlen
echo 1024 > /proc/sys/net/ipv4/tcp_min_snd_mss
echo 1024 > /proc/sys/net/ipv4/tcp_min_tso_segs
echo 1024 > /proc/sys/net/ipv4/tcp_probe_threshold
echo 900 > /proc/sys/net/ipv4/tcp_pacing_ca_ratio
echo 900 > /proc/sys/net/ipv4/tcp_pacing_ss_ratio
echo 600 > /proc/sys/net/ipv4/tcp_max_reordering
echo 536 > /proc/sys/net/ipv4/route/min_adv_mss
echo 10 > /proc/sys/net/ipv4/tcp_reordering
echo 10 > /proc/sys/net/ipv4/tcp_comp_sack_nr
echo 8 > /proc/sys/net/ipv4/tcp_window_scaling
echo 8 > /proc/sys/net/ipv4/tcp_tso_win_divisor
echo 8 > /proc/sys/net/ipv4/tcp_adv_win_scale
echo 2 > /proc/sys/net/ipv4/tcp_mtu_probing
echo 2 > /proc/sys/net/ipv4/tcp_orphan_retries
echo 1 > /proc/sys/net/ipv4/tcp_workaround_signed_windows
echo 1 > /proc/sys/net/ipv4/tcp_rfc1337
echo 1 > /proc/sys/net/ipv4/ip_forward_use_pmtu
echo 1 > /proc/sys/net/ipv4/ip_forward
echo 1 > /proc/sys/net/ipv4/tcp_tw_reuse
echo 1 > /proc/sys/net/ipv4/tcp_no_metrics_save
echo 1 > /proc/sys/net/ipv4/tcp_early_retrans
echo 1 > /proc/sys/net/ipv4/tcp_rx_skb_cache
echo 0 > /proc/sys/net/ipv4/tcp_abort_on_overflow
echo 0 > /proc/sys/net/ipv4/tcp_ecn_fallback
echo 0 > /proc/sys/net/ipv4/tcp_timestamps
echo 0 > /proc/sys/net/ipv4/tcp_moderate_rcvbuf
echo 0 > /proc/sys/net/ipv4/tcp_ecn
echo 0 > /proc/sys/net/ipv4/tcp_slow_start_after_idle
echo 0 > /proc/sys/net/ipv4/tcp_frto
echo 0 > /proc/sys/net/ipv4/tcp_autocorking
#"5"
### "GC" ###
echo 65536 > /sys/module/nf_conntrack/parameters/hashsize
echo 65535 > /proc/sys/net/ipv4/neigh/default/gc_thresh3
echo 65536 > /sys/module/nf_conntrack/parameters/hashsize
echo 16384 > /proc/sys/net/ipv4/neigh/default/gc_thresh2
echo 8192 > /proc/sys/net/ipv4/neigh/default/gc_thresh1
##############################
### "DESATIVAR IPV6" ###
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
echo 1 > /proc/sys/net/ipv6/conf/default/disable_ipv6
echo 1 > /proc/sys/net/ipv6/conf/lo/disable_ipv6
echo 1 > /proc/sys/net/ipv6/conf/lo/disable_ipv6
##############################
