#!/bin/bash
#'Eth?'#
for q in $(ls /sys/class/net/eth*/queues/rx-*/rps_cpus); do echo f > $q; done
for q in $(ls /sys/class/net/eth*/queues/rx-*/rps_flow_cnt); do echo 65535 > $q; done
for q in $(ls /sys/class/net/eth*/queues/tx-*/xps_cpus); do echo f > $q; done
#'Lp'#
for q in $(ls /sys/class/net/lo*/queues/rx-*/rps_cpus); do echo f > $q; done
for q in $(ls /sys/class/net/lo*/queues/rx-*/rps_flow_cnt); do echo 65535 > $q; done
for q in $(ls /sys/class/net/lo*/queues/tx-*/xps_cpus); do echo f > $q; done
#'Exit'#
echo 65535 > /proc/sys/net/core/rps_sock_flow_entries
echo tsc > /sys/devices/system/clocksource/clocksource0/current_clocksource
echo never > /sys/kernel/mm/transparent_hugepage/enabled
#'Frequencie'#
echo 4400000 > /scaling_max_freq
echo 1 > /sys/module/processor/parameters/ignore_ppc
