#!/bin/bash
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
[[ ! -e /usr/lib/sshplus ]] && rm -rf /bin/menu > /dev/null 2>&1
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "\033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;34m/"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "\033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
IP=$(cat /etc/IP)
x="ok"
menu ()
{
velocity () {
aguarde () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
[[ ! -d /etc/SSHPlus ]] && rm -rf /bin/menu
${comando[0]} > /dev/null 2>&1
${comando[1]} > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mCARREGANDO \033[1;37m\033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;34m/"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mCARREGANDO \033[1;37m\033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m\033[1;32m CONCLUIDO !\033[1;37m"
tput cnorm
}
fun_tst () {
speedtest --share > speed
}
echo ""
echo -e "   \033[1;36mTESTANDO A VELOCIDADE DE BANDA !\033[0m"
echo ""
aguarde 'fun_tst'
echo ""
png=$(cat speed | sed -n '5 p' |awk -F : {'print $NF'})
down=$(cat speed | sed -n '7 p' |awk -F :  {'print $NF'})
upl=$(cat speed | sed -n '9 p' |awk -F :  {'print $NF'})
lnk=$(cat speed | sed -n '10 p' |awk {'print $NF'})
echo -e "\033[0;37m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;33mDOWN:\033[1;37m[ $down ]    \033[1;33m UP: \033[1;37m[ $upl ]     \033[1;33mPING: \033[1;37m[ $png ]"
echo -e ""
echo -e "\033[1;33mLINK: \033[1;37m$lnk\033[0m"
echo -e "\033[0;37m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
rm -rf $HOME/speed
}

#]
function onapp1 () {
clear
echo -e "\n\033[1;32mINICIANDO O ONLINE APP... \033[0m"
echo ""
apt install apache2 -y > /dev/null 2>&1
sed -i "s/Listen 80/Listen 8888/g" /etc/apache2/ports.conf >/dev/null 2>&1
service apache2 restart
rm -rf /var/www/html/server >/dev/null 2>&1
mkdir /var/www/html/server >/dev/null 2>&1
fun_bar 'screen -dmS onlineapp onlineapp' 'sleep 3'
[[ $(grep -wc "onlineapp" /etc/autostart) = '0' ]] && {
echo -e "ps x | grep 'onlineapp' | grep -v 'grep' && echo 'ON' || screen -dmS onlineapp onlineapp" >> /etc/autostart
} || {
sed -i '/onlineapp/d' /etc/autostart
echo -e "ps x | grep 'onlineapp' | grep -v 'grep' && echo 'ON' || screen -dmS onlineapp onlineapp" >> /etc/autostart
}
IP=$(wget -qO- ipv4.icanhazip.com) >/dev/null 2>&1
echo -e "\n\033[1;32m  ONLINE APP ATIVO !\033[0m"
echo -e "\033[1;31m \033[1;33mURL de Usuários Online para usar no App\033[0m"
echo -e " http://$IP:8888/server/online"
sleep 10s
menu
}
function onapp2 () {
clear
echo -e "\033[1;32mPARANDO O ONLINE APP... \033[0m"
echo ""
fun_stponlineapp () {
sleep 1s
screen -r -S "onlineapp" -X quit
screen -wipe 1>/dev/null 2>/dev/null
[[ $(grep -wc "onlineapp" /etc/autostart) != '0' ]] && {
sed -i '/onlineapp/d' /etc/autostart
}
sleep 1s
}
fun_bar 'fun_stponlineapp' 'sleep 3'
rm -rf /var/www/html/server >/dev/null 2>&1
echo -e "\n\033[1;31m ONLINE APP PARADO !\033[0m"
sleep 3s
menu
}
function onapp_ssh () {
[[ $(ps x | grep "onlineapp"|grep -v grep |wc -l) = '0' ]] && onapp1 || onapp2
}

#menu2
menu2 (){
stsl=$(ps x | grep "limiter"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON ◉)" || echo -e "\033[1;31m(OFF ○)")
stsu=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON ◉)" || echo -e "\033[1;31m(OFF ○)")
stson=$(ps x | grep "onlineapp"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON ◉) " || echo -e "\033[1;31m(OFF ○) ")
stsbot=$(ps x | grep "bot_plus"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON ◉)" || echo -e "\033[1;31m(OFF ○)")
autm=$(grep "menu;" /etc/profile > /dev/null && echo -e "\033[1;32m(ON ◉) " || echo -e "\033[1;31m(OFF ○)")
_swap1=$(free -h | grep -i swap | awk {'print $2'})
[[ -e /etc/Plus-torrent ]] && stsf=$(echo -e "\033[1;32m(ON ◉)") || stsf=$(echo -e "\033[1;31m(OFF ○)")
ram1=$(free -h | grep -i mem | awk {'print $2'})
cpucores=$(grep -c cpu[0-9] /proc/stat)
atual=$(cat /proc/sys/net/core/rmem_default)
atual2=$(cat /proc/sys/net/ipv4/tcp_congestion_control)
clear
echo -e "\033[0;34m------------------------------------"
echo -e "\033[1;34m<\033[1;37m01 ×\033[1;34m> \033[1;37m[ Bad-Vpn UDP ]  $stsu\033[0;32m"
echo -e "\033[1;34m<\033[1;37m02 ×\033[1;34m> \033[1;37m[ Bot Telegram ] $stsbot\033[0;32m"
echo -e "\033[1;34m<\033[1;37m03 ×\033[1;34m> \033[1;37m[ Limitar Usuarios ] $stsl\033[0;32m"
echo -e "\033[1;34m<\033[1;37m04 ×\033[1;34m> \033[1;37m[ Ativar Auto Menu ]  $autm\033[0;32m"
echo -e "\033[0;34m------------------------------------"
echo -e "\033[1;34m<\033[1;37m04 ×\033[1;34m> \033[1;31m\033[1;37m[ Monitorar Trafego Com Slurm ]\033[0;32m"
echo -e "\033[1;34m<\033[1;37m05 ×\033[1;34m> \033[1;31m\033[1;37m[ Monitorar Sistema Com Htop ]\033[0;32m"
echo -e "\033[1;34m<\033[1;37m06 ×\033[1;34m> \033[1;31m\033[1;37m[ Monitorar Sistema Com Glances ]\033[0;32m"
echo -e "\033[1;34m<\033[1;37m07 ×\033[1;34m> \033[1;31m\033[1;37m[ Monitorar Sessões Com NetHogs ]\033[0;32m"
echo -e "\033[0;34m------------------------------------"
echo -e "\033[1;34m<\033[1;37m09 ×\033[1;34m> \033[1;31m\033[1;37m[ Criar Memoria Swapping ] \033[1;32mSWAP \033[1;37m$swap1"
echo -e "\033[1;34m<\033[1;37m10 ×\033[1;34m> \033[1;31m\033[1;37m[ Reiniciar Servidor ] \033[1;32mATIVO \033[1;37m$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}')"
echo -e "\033[1;34m<\033[1;37m11 ×\033[1;34m> \033[1;31m\033[1;37m[ Alterar Senha Root Atual ]\033[0;32m"
echo -e "\033[1;34m<\033[1;37m12 ×\033[1;34m> \033[1;31m\033[1;37m[ Informações Do Servidor ] \033[1;32mRAM\033[1;37m $ram1\033[0;32m \033[1;37m+ \033[1;32mCPU\033[1;37m $cpucores"
echo -e "\033[0;34m------------------------------------"
echo -e "\033[1;34m<\033[1;37m13 ×\033[1;34m> \033[1;31m\033[1;37m[ Atualizar Para Corrigir Erros ]"
echo -e "\033[1;34m<\033[1;37m14 ×\033[1;34m> \033[1;31m\033[1;37m[ Remover Todo O Conteudo Instalado ]"
echo -e "\033[0;34m------------------------------------"
echo -e "\033[1;34m<\033[1;37m00 ×\033[1;34m> \033[1;31m\033[1;37m[ Voltar Ao Menu Principal ]\033[0;32m"
echo -e "\033[0;34m------------------------------------"
read x
case "$x" in
1 | 01)
clear
badvpn
;;
2 | 02)
clear
botssh
;;
3 | 03)
limit_ssh
menu2
;;
4 | 04)
autoexec
;;
5 | 05)
clear
  echo -e "\033[1;33mPARA SAIR CLICK CTRL + C\033[1;36m"
sleep 5s
slurm -i eth0
clear
menu2
;;
6 | 06)
clear
echo -e "\033[1;33mPARA SAIR CLICK CTRL + C\033[1;36m"
sleep 5s
htop
clear
menu2
;;
7 | 07)
clear
echo -e "\033[1;33mPARA SAIR CLICK CTRL + C\033[1;36m"
sleep 5s
glances
clear
menu2
;;
8 | 08)
clear
echo -e "\033[1;33mPARA SAIR CLICK CTRL + C\033[1;36m"
sleep 5s
 nethogs -v 3
clear
menu2
;;
9 | 09)
clear
swapmemory
menu2
;;
10 | 10)
clear
echo -e "\033[1;33mSERVIDOR REINICIANDO...\033[1;36m"
sleep 5s
reboot
;;
11 | 11)
clear
senharoot
sleep 5s
menu2
;;
12 | 12)
clear
detalhes
 echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
menu2
;;
13 | 13)
clear
atualizar
;;
14 | 14)
clear
delscript
;;
0 | 00)
clear
menu
;;
   *)
menu2
esac
}
while true $x != "ok"
do
#limiter
function limit1 () {
   clear
   echo -e "\n\033[1;32mINICIANDO O LIMITADOR SSH... \033[0m"
   echo ""
   fun_bar 'screen -dmS limiter limiter' 'sleep 3'
   [[ $(grep -wc "limiter" /etc/autostart) = '0' ]] && {
       echo -e "ps x | grep 'limiter' | grep -v 'grep' && echo 'ON' || screen -dmS limiter limiter" >> /etc/autostart
   } || {
       sed -i '/limiter/d' /etc/autostart
	   echo -e "ps x | grep 'limiter' | grep -v 'grep' && echo 'ON' || screen -dmS limiter limiter" >> /etc/autostart
   }
   echo -e "\n\033[1;32m  LIMITADOR SSH ATIVO !\033[0m"
   sleep 2
   menu2
}
function limit2 () {
   clear
   echo -e "\033[1;33mPARANDO O LIMITADOR SSH... \033[0m"
   echo ""
   fun_stplimiter () {
      sleep 1
      screen -r -S "limiter" -X quit
      screen -wipe 1>/dev/null 2>/dev/null
      [[ $(grep -wc "limiter" /etc/autostart) != '0' ]] && {
          sed -i '/limiter/d' /etc/autostart
      }
      sleep 1
   }
   fun_bar 'fun_stplimiter' 'sleep 3'
   echo -e "\n\033[1;31m LIMITADOR SSH PARADO !\033[0m"
   sleep 2
   menu2
}
function limit_ssh () {
[[ $(ps x | grep "limiter"|grep -v grep |wc -l) = '0' ]] && limit1 || limit2
}
stsl=$(ps x | grep "limiter"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON ◉)" || echo -e "\033[1;31m(OFF ○)")
stsu=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON ◉)" || echo -e "\033[1;31m(OFF ○)")
stson=$(ps x | grep "onlineapp"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON ◉) " || echo -e "\033[1;31m(OFF ○) ")
stsbot=$(ps x | grep "bot_plus"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON ◉)" || echo -e "\033[1;31m(OFF ○)")
autm=$(grep "menu;" /etc/profile > /dev/null && echo -e "\033[1;32m(ON ◉) " || echo -e "\033[1;31m(OFF ○)")
function autoexec () {
if grep "menu;" /etc/profile > /dev/null; then
clear
echo -e "\033[1;33mDESATIVANDO AUTO [ MENU ]\033[0m"
offautmenu () {
sed -i '/menu;/d' /etc/profile
}
 echo ""
fun_bar 'offautmenu'
echo ""
echo -e "\033[1;31mAUTO [ MENU ] DESATIVADO!\033[0m"
sleep 1.5s
menu2
else
clear
echo -e "\033[1;33mATIVANDO AUTO [ MENU ]\033[0m"
autmenu () {
grep -v "^menu;" /etc/profile > /tmp/tmpass && mv /tmp/tmpass /etc/profile
echo "menu;" >> /etc/profile
}
echo ""
fun_bar 'autmenu'
echo ""
echo -e "\033[1;32mAUTO [MENU] ATIVADO!\033[0m"
sleep 1.5s
menu2
fi
}
if [[ "$(grep -c "Ubuntu" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f2 /etc/issue.net |awk -F "." '{print $1}')
elif [[ "$(grep -c "Debian" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f3 /etc/issue.net)
else
system=$(cut -d' ' -f1 /etc/issue.net)
fi
_ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)
[[ "$(cat /etc/SSHPlus/Exp)" != "" ]] && _expuser=$(cat /etc/SSHPlus/Exp) || _expuser="0"
[[ -e /etc/openvpn/openvpn-status.log ]] && _onop=$(grep -c "10.8.0" /etc/openvpn/openvpn-status.log) || _onop="0"
[[ -e /etc/default/dropbear ]] && _drp=$(ps aux | grep dropbear | grep -v grep | wc -l) _ondrp=$(($_drp - 1)) || _ondrp="0"
ram1=$(free -h | grep -i mem | awk {'print $2'})
ram2=$(free -h | grep -i mem | awk {'print $4'})
ram3=$(free -h | grep -i mem | awk {'print $3'})
ram4=$(free | awk '/Mem/{printf("%.1f"), $3/($2+.000000001)*100}')
swap1=$(free -h | grep -i swap | awk {'print $2'})
swap2=$(free -h |grep -i swap |awk {'print $4'})
swap3=$(free -h | grep -i swap | awk {'print $3'})
swap4=$(free | awk '/Swap/{printf("%.1f"), $3/($2+.000000001)*100}';)
modelo=$(cat /proc/cpuinfo |grep "model name" |uniq |awk -F : {'print $2'})
Kernel1=$(uname -s)
Kernel2=$(uname -m)
cpucores=$(grep -c cpu[0-9] /proc/stat)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
_onli=$(($_ons + $_onop + $_ondrp))
_usop=$(printf '%-1s' "$(mpstat | awk 'END{print 100-$NF"%"}')")
_core=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
_system=$(printf '%-14s' "$system")
_hora=$(printf '%(%H:%M:%S)T')
_onlin=$(printf '%-5s' "$_onli")
_userexp=$(printf '%-5s' "$_expuser")
_tuser=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
printf "%(%m-%d-%Y %H:%M:%S)T\n" $(date +%s)
porta_7300=$(netstat -nplt | grep 'badvpn' | awk {'print $4'} | cut -d: -f2 | xargs)
porta_80=$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)
GHZ=`lscpu |awk -F : '($1=="CPU MHz") {printf "%3.2fGHz\n", $2/1000}'`
system=$(cat /etc/issue.net)
clear -x
echo -e "\033[1;37m$system  \033[1;32mACKHTTP SERVER"
echo -e "\033[0;34m------------------------------------"
echo -e "\033[1;36m[RAM] \033[1;37m$ram4 \033[1;37m   ||||    \033[1;36m[CPU]\033[1;37m $_usop"
echo -e "\033[0;34m------------------------------------"
echo -e "\033[1;34m<\033[1;37m01 ×\033[1;34m> \033[1;37m[ Adicionar Login ]\033[1;36m ADD \033[1;37m$_tuser \033[0;32m"
echo -e "\033[1;34m<\033[1;37m02 ×\033[1;34m> \033[1;37m[ Alterar Senha ]\033[0;32m"
echo -e "\033[1;34m<\033[1;37m03 ×\033[1;34m> \033[1;37m[ Alterar Data ]\033[0;32m"
echo -e "\033[1;34m<\033[1;37m04 ×\033[1;34m> \033[1;37m[ Alterar Limites ]\033[0;32m"
echo -e "\033[1;34m<\033[1;37m05 ×\033[1;34m> \033[1;37m[ Apagar Logins ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m06 ×\033[1;34m> \033[1;37m[ Apagar Expirados ] \033[1;31mExp \033[1;37m$_userexp"
echo -e "\033[0;34m------------------------------------"
echo -e "\033[1;34m<\033[1;37m07 ×\033[1;34m> \033[1;37m[ Relatorio De Logins ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m08 ×\033[1;34m> \033[1;37m[ Monitorar Conectados ] \033[1;32mOn \033[1;37m$_onlin\033[0;32m"
echo -e "\033[1;34m<\033[1;37m09 ×\033[1;34m> \033[1;37m[ Restaurar Backup SSH ]\033[0;32m"
echo -e "\033[1;34m<\033[1;37m10 ×\033[1;34m> \033[1;37m[ Banner SSH ]\033[0;32m"
echo -e "\033[0;34m------------------------------------"
echo -e "\033[1;34m<\033[1;37m11 ×\033[1;34m> \033[1;37mConexão >> \033[1;33mV2ray,Ws,OpenVpn"
echo -e "\033[1;34m<\033[1;37m12 ×\033[1;34m> \033[1;37mTuning >> \033[1;33mTcp,Dns,Cpu"
echo -e "\033[1;34m<\033[1;37m13 ×\033[1;34m> \033[1;37mSistema >> \033[1;33mBadVpn,Swap,Htop"
echo -e "\033[0;34m------------------------------------\033[1;37m"
read x
case "$x" in
   1 | 01)
   clear
   criarusuario
   echo -ne "\n\033[1;33mENTER \033[1;33mPARA VOLTAR AO \033[1;33mMENU!\033[0m"; read
   ;;
   2 | 02)
   clear
   alterarsenha
   sleep 3s
   ;;
   3 | 03)
   clear
   mudardata
   sleep 3s
   ;;
   4 | 04)
   clear
   alterarlimite
   sleep 3s
   ;;
   5 | 05)
   clear
   remover
   sleep 5s
   ;;
   6 | 06)
   clear
   expcleaner;uexpired
   echo ""
   sleep 3s
   ;;
   7 | 07)
   clear
   infousers
   echo -ne "\n\033[1;33mENTER \033[1;33mPARA VOLTAR AO \033[1;33mMENU!\033[0m"; read
   ;;
   8 | 08)
   clear
   sshmonitor
   echo -ne "\n\033[1;33mENTER \033[1;33mPARA VOLTAR AO \033[1;33mMENU!\033[0m"; read
   ;;
   9 | 09)
   clear
   userbackup
   sleep 3s
   ;;
   10 | 10)
   clear
   banner
   ;;
   11 | 11)
   clear
   conexao
   ;;
   12 | 12)
   clear
   cd /bin/ && mtuning
;;
   13 | 13)
    clear
    menu2
   ;;
   0|00)
   clear
   exit && exit
   ;;
   *)
esac
done
}
menu
#fim

